---
- hosts: localhost
  sudo: yes
  tasks:
    - name: Upgrade packages 
      apt:
        name: "*"
        update_cache: yes
        state: latest

    - name: Install vim
      apt:
        name: vim

    - name: Install htop 
      apt:
        name: htop 

    - name: Install git
      apt:
        name: git

    - name: Install openjdk 11
      apt:
        name: "openjdk-11-*"

    - name: Install docker deps 
      script: install_docker_deps.sh

    - name: Install maven
      apt:
        name: maven

    - name: Docker key
      apt_key: 
        url: "https://download.docker.com/linux/ubuntu/gpg"

    - name: Add docker repo
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} test"
        state: present
        update_cache: yes

    - name: Install docker-ce
      apt:
        name: docker-ce

    - name: Install docker-ce-cli
      apt:
        name: docker-ce-cli

    - name: Install containerd.io 
      apt:
        name: containerd.io 

    - name: Add vakiovale to docker group
      user:
        name: vakiovale 
        group: docker

    - name: Install pip3
      apt:
        name: python3-pip

    - name: Install docker-compose
      become: true
      become_user: vakiovale 
      pip:
        name: docker-compose

    - name: Install nvm
      become: true
      become_user: vakiovale 
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
